/* -*- Mode:Prolog; coding:utf-8; -*- */
%% Generated by class UpdateRoutePeriode on 2022-05-02 13:51:25.231

:- module( route_period, [ route_period/4 ] ).

% Xmas routes before winter routes
% Easter routes before winter routes

%% Route module 'nil' in route_period means that the route module is not implemented yet
%% Important to have dummy route modules to give message of no routes for this date

%%%% ACTUAL  ROUTES              START-DATE           END-DATE (sorted!)

route_period(   tt, r160_220404, date(2022,04,04),   date(2022,08,20) ).    %% Auto Update: 2022-05-02
